-- NOTA: le migrazioni 0023-0028 sono state applicate direttamente sul
-- progetto Supabase tramite connettore (visibili nella cronologia
-- migrazioni del pannello). Contengono:
--   0023 globali, globale_formazioni, globale_eventi + RLS
--   0024 rotazione/punteggio/annullamento del globale
--   0025 analisi rotazioni globale + chiusura con proposte valutazione
--   0026 rimozione del tetto arbitrario di chiamate AI
--   0027 abilitazione realtime sulle tabelle di scouting
--   0028 rotazione registrata negli eventi partita + analisi rotazioni
-- Questo file è un segnaposto per mantenere allineata la cronologia
-- del repository; rieseguire setup_supabase.sql resta sicuro.
